name: Docs

"on":
  push:
    branches:
      - main
      - master
      - "tickets/**"
      - "u/**"
      - "!u/neophile"
    paths:
      - "CHANGELOG.rst"
      - "docs/**"
      - "src/**.py"
    tags:
      - "*"
  pull_request:
    paths:
      - "CHANGELOG.rst"
      - "docs/**"
      - "src/**.py"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install tox and LTD Conveyor
        run: pip install tox ltd-conveyor

      - name: Install graphviz
        run: sudo apt-get install graphviz

      - name: Run tox
        run: tox -e docs

      - name: Upload to LSST the Docs
        env:
          LTD_USERNAME: ${{ secrets.LTD_USERNAME }}
          LTD_PASSWORD: ${{ secrets.LTD_PASSWORD }}
        run: ltd upload --product kafka-aggregator --gh --dir docs/_build/html
        if: github.event_name != 'pull_request'
